name: Check AWS s3 connection
run-name: "Test S3 connection"
on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
env:
  AWS_S3_BUCKET: "test-3432432432423"
jobs:
  s3-connection:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: github-actions-labsadmanrock
          aws-region: ${{ github.event.inputs.aws_region }}
          output-credentials: true
      - name: See assume role 
        run: |
          aws sts get-caller-identity
      - name: Test S3 connection
        id: s3-connection
        run: |
         aws s3 ls s3://${AWS_S3_BUCKET}

          
